This is arbitrary text, and this is 
a snippet 'pi=3.14159', delimited 
with characters from the first line.
In this snippet, the 3.14159 variable is 
defined. After a variable is defined, 
it can be referenced in other snippets, 
like here:  6.28318.

A snippet can take several lines. It 
is like a python script, but saved 
directly in the template file. It can
access variables defined in previous
snippets. 
'
from math import cos
print
for x in [0, 0.3, 0.7, 1.]:
    print x, cos(pi*x)
'
0 1.0
0.3 0.587785896332
0.7 -0.587783749532
1.0 -0.999999999996


The standard output generated by the 
snippet, if any, will be inserted 
into the resulting file right after
the snippet.
 
